<?php

/**
 * @file
 * Geocluster extension for geofield and maps.
 */

/**
 * Implements hook_views_api().
 */
function geocluster_views_api() {
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'geocluster') . '/views',
  );
}

/**
 * Invokes clustering after the views query has been executed.
 *
 * Implements hook_views_post_execute_query.
 */
function geocluster_views_post_execute_query(&$view) {

  foreach ($view->field as $key => $my_field) {
    if ($my_field->definition['handler'] == 'geocluster_handler_field_geofield') {
      $field = $my_field;
    }
  }
  if (!isset($field)) {
    return;
  }

  $cluster_distance = $field->options['cluster_distance'];

  if ($view->style_plugin->plugin_name == 'leaflet') {
    $map = $view->style_plugin->options['map'];
    $info =  leaflet_map_get_info($map);
    $zoom = $info['settings']['zoom'];
  }
  else {
    // geofield_map
    $style_options = $view->display_handler->display->display_options['style_options'];
    $zoom = $style_options['geofield_map_zoom'];
  }

  $cluster = new Geocluster($cluster_distance, $zoom, $field);
  $cluster->cluster($view);
}


/**
 * Invokes clustering after the views query has been executed.
 *
 * Implements hook_views_post_execute_query.
 */
/*
function geocluster_views_object_types_alter(&$object_types) {
  $object_types = array(
    'cluster' => array(
      'title' => t('Cluster behavior'),
      'ltitle' => t('cluster behavior'),
      'stitle' => t('Cluster behavior'),
      'lstitle' => t('Cluster behavior'),
      'plural' => 'cluster',
    ),
  ) + $object_types;
  return $object_types;
}
*/
