<?php

/**
 * @file
 * Geocluster extension for geofield and maps.
 */

/**
 * Implements hook_views_api().
 */
function geocluster_views_api() {
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'geocluster') . '/views',
  );
}

function geocluster_views_post_execute_query(&$view) {
  foreach ($view->field as $key => $my_field) {
    if ($my_field->definition['handler'] == 'geocluster_handler_field_geofield') {
      $field = $my_field;
    }
  }
  if (!isset($field)) {
    return;
  }

  $style_options = $view->display_handler->display->display_options['style_options'];
  $zoom = $style_options['geofield_map_zoom'];

  $cluster = new Geocluster($zoom, $field);
  $cluster->cluster($view);
  dpm($view);

}
