<?php

/**
 * Implements hook_views_api().
 */
function geocluster_solr_views_api() {
  return array(
    'api' => 3.0,
  );
}

/**
 * Implements hook_geocluster_algorithm().
 */
function geocluster_solr_geocluster_algorithm() {
  return array(
    'geocluster_solr' => array(
      'handler' => array(
        'label' => t('Search API Solr based clustering algorithm'),
        'class' => 'SolrGeohashGeoclusterAlgorithm',
      ),
    ),
  );
}

/**
 * Implements hook_search_api_data_type_info().
 */
function geocluster_solr_search_api_data_type_info() {
  return array(
    'geohash' => array(
      'name' => t('Geohash'),
    ),
    'location' => array(
      'name' => t('Location'),
    ),
  );
}

/**
 * Implements hook_search_api_service_info().
 */
function geocluster_solr_search_api_service_info() {
  $services['geocluster_solr_service'] = array(
    'name' => t('Geocluster Solr service'),
    'description' => t('<p>Geocluster-specific index based on the standard Search API Solr server.</p>'),
    'class' => 'GeoclusterSearchApiSolrService',
  );
  return $services;
}
