<?php


/**
 * Implements hook_leaflet_map_info() to return a default map.
 *
 * @return array
 */
function geocluster_test_leaflet_map_info() {
  return array(
    'local control' =>
    array(
      'label' => 'local control',
      'description' => t(''),
      'center' => array(
        'lon' => 14.32411,
        'lat' => 47.88101
      ),
      'settings' => array(
        'zoom' => 7,
        'minZoom' => 0,
        'maxZoom' => 8,
        'dragging' => TRUE,
        'touchZoom' => TRUE,
        'scrollWheelZoom' => TRUE,
        'doubleClickZoom' => TRUE,
        'zoomControl' => TRUE,
        'attributionControl' => TRUE,
        'trackResize' => TRUE,
        'fadeAnimation' => TRUE,
        'zoomAnimation' => TRUE,
        'closePopupOnClick' => TRUE,
      ),
      'layers' => array(
        'control_room' => array(
          'type' => 'tilestream',
          'urlTemplate' => 'http://localhost:8888/1.0.0/control_room/{z}/{x}/{y}.png',
          // 'otions' => array(
          //  'attribution' => 'OSM Mapnik'
          // )
        ),
      ),
    ),
  );
}

function geocluster_test_preprocess_leaflet_map($variables) {
  drupal_add_js(
    drupal_get_path('module', 'geocluster_test') . '/geocluster_test.js',
    // Add our script after leaflet.drupal.js.
    array('weight' => 5)
  );
}
