<?php


/**
 * Implements hook_leaflet_map_info() to return a default map.
 *
 * @return array
 */
function geocluster_test_leaflet_map_info() {
  return array(
    'local control' =>
    array(
      'label' => 'local control',
      'description' => t(''),
      'settings' => array(
        'zoom' => 4,
        'minZoom' => 0,
        'maxZoom' => 8,
        'dragging' => TRUE,
        'touchZoom' => TRUE,
        'scrollWheelZoom' => TRUE,
        'doubleClickZoom' => TRUE,
        'zoomControl' => TRUE,
        'attributionControl' => TRUE,
        'trackResize' => TRUE,
        'fadeAnimation' => TRUE,
        'zoomAnimation' => TRUE,
        'closePopupOnClick' => TRUE,
      ),
      'layers' => array(
        'control_room' => array(
          'type' => 'tilestream',
          'urlTemplate' => 'http://localhost:8888/1.0.0/control_room/{z}/{x}/{y}.png',
          // 'otions' => array(
          //  'attribution' => 'OSM Mapnik'
          // )
        ),
      ),
    ),
  );
}
